// flow-typed signature: 740424f86db559aaacaa165c74610f99
// flow-typed version: <<STUB>>/babel-plugin-transform-commonjs_v^1.1.6/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-commonjs/dist' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-commonjs/test/_utils' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-commonjs/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-commonjs/dist/index' {
  declare module.exports: $Exports<'babel-plugin-transform-commonjs/dist'>;
}
declare module 'babel-plugin-transform-commonjs/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-commonjs/dist'>;
}
declare module 'babel-plugin-transform-commonjs/test/_utils.js' {
  declare module.exports: $Exports<'babel-plugin-transform-commonjs/test/_utils'>;
}
declare module 'babel-plugin-transform-commonjs/test/index' {
  declare module.exports: $Exports<'babel-plugin-transform-commonjs/test'>;
}
declare module 'babel-plugin-transform-commonjs/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-commonjs/test'>;
}
